In [38]:
import numpy as np

In [39]:
def entropy(s):
    '''
    Calculates the entropy given list of target(binary) variables
    '''
    # Write your code here
    
    # Caclulate entropy
    entropy = 0
    p = np.mean(s)
    if p == 0 or p == 1:
        return 0.0
    entropy = p*np.log2(p)+(1-p)*np.log2(1-p)
    
    #Your code ends here
    
    return -entropy

In [40]:
def information_gain(parent, left_child, right_child):
    
    '''
    Compute information gain given left_child target variables (list), right_child target variables(list) and their parent targets(list)
    '''
    
    info_gain=None
    # Write your code here
    parent_entropy = entropy(parent)
    left_child_entropy = entropy(left_child)
    right_child_entropy = entropy(right_child)
    n1,n2 = len(left_child),len(right_child)
    n = len(parent)
    weighted_children = (n1/n)*left_child_entropy + (n2/n)*right_child_entropy
    info_gain = parent_entropy - weighted_children
    
    #Your code ends here
    return info_gain

In [41]:
entropy([1,1,1,1,1])

0.0

In [42]:
y_parent = np.array([0, 0, 0, 1, 0, 1, 1,1,1,1])  # H=0.971
y_left   = np.array([1,0,0,0])           # H=0.0  
y_right  = np.array([0, 1, 1,1,1,1])         # H=0.0
ig = information_gain(y_parent, y_left, y_right)
ig

np.float64(0.256425891682003)

In [43]:
features = np.array([0.58,0.9,0.45,0.18,0.5,0.12,0.31,0.09,0.24,0.83])
label = np.array([1,0,0,0,0,0,1,0,1,1])

In [44]:
label[features<0.58]

array([0, 0, 0, 0, 1, 0, 1])

In [45]:
x = np.array([[1,2],[1,2],[1,2]])
x[:,:-1]

array([[1],
       [1],
       [1]])

In [46]:
predict = [0,0,0,1,0,0,1,1]
np.bincount(predict).argmax()
predict.count

<function list.count(value, /)>

In [47]:
classes_data = {0:10,1:15,2:3}
classes_data.items()
max(classes_data.items(),key = lambda x:x[1])
classes_data.get

<function dict.get(key, default=None, /)>

In [48]:
x = np.array([0]*420 + [1]*80)
x

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [49]:
y = np.zeros(500)
y

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0.

In [50]:
y[np.where(x==0)[0][:300]]=1
y

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1.

In [51]:
y[np.where(x==1)[0][:40]]=1
np.bincount(y.astype(int))

array([160, 340])

In [52]:
from sklearn.linear_model import LogisticRegression

ModuleNotFoundError: No module named 'sklearn'

In [ ]:
model = LogisticRegression()
model.fit(x.reshape(-1,1),y.reshape(-1,1))


/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/utils/validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression()

In [ ]:
model.coef_,model.intercept_

(array([[-0.86318297]]), array([0.90625126]))

In [ ]:
import numpy as np
np.log2(0.9)

-0.15200309344504995

In [ ]:
y_true = np.array([1,0,2])
y_pred = np.array([1,0,1])

In [ ]:
classes = np.unique(y_true)
n_classes = len(np.unique(y_true))
n_classes

3

In [ ]:
confusion_matrix = np.zeros((n_classes,n_classes))
confusion_matrix

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
label_to_idx = {c: i for i, c in enumerate(classes)}
label_to_idx

{np.int64(0): 0, np.int64(1): 1, np.int64(2): 2}

In [ ]:
for true,pred in zip(y_true,y_pred):
    confusion_matrix[true,pred] += 1
print(confusion_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]]


In [ ]:
tp = np.diag(confusion_matrix).astype(float)
tp

array([1., 1., 0.])

In [ ]:
pred_sum = np.sum(confusion_matrix,axis=0).astype(float)
pred_sum

array([1., 2., 0.])

In [ ]:
true_sum = np.sum(confusion_matrix,axis=1).astype(float)
true_sum

array([1., 1., 1.])

array([0., 0., 0.])

In [58]:
precision = np.divide(tp,pred_sum,where=pred_sum!=0,out=np.zeros_like(tp))
precision

array([1. , 0.5, 0. ])

In [60]:
recall =np.divide(tp,true_sum,where=true_sum!=0,out=np.zeros_like(tp))
recall

array([1., 1., 0.])

In [63]:
f1 = np.divide(2*precision*recall,(precision+recall),out=np.zeros_like(precision),where=(precision+recall)!=0)
f1

array([1.        , 0.66666667, 0.        ])